---
- name: Install python-psutil package
  apt:
    name: python3-psutil

- name: Copy wallpaper file
  become_user: "{{ lookup('env','USER') }}"
  copy: 
    src: files/wallpaper.jpg
    dest: "{{ lookup('env','HOME') }}/.wallpaper.jpg"
    owner: "{{ lookup('env','USERNAME') }}"
    group: "{{ lookup('env','USERNAME') }}"
    mode: 0600

- name: Set GNOME wallpaper
  become_user: "{{ lookup('env','USER') }}"
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/{{ lookup('env','USERNAME') }}/.wallpaper.jpg'"
