---
# ansible-playbook -vv -K playbook.yaml --diff --tags vbox
- name: main
  hosts: 127.0.0.1
  connection: local
  diff: yes
  become: yes
  roles:
  - role: base-packages
    tags: [base]
  - role: dev
    tags: [dev]
 