---
- name: virtual-box | Install oracle gpg key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present

- name: virtual-box | Add apt repository for VirtualBox
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian focal contrib
    state: present

- name: virtual-box | Install VirtualBox
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - virtualbox-6.1

- name: virtual-box | Download VirtualBox extension pack
  get_url:
    url: "https://download.virtualbox.org/virtualbox/6.1.18/Oracle_VM_VirtualBox_Extension_Pack-6.1.18.vbox-extpack"
    dest: /tmp/
    force: yes
  register: download_result

- name: virtual-box | Output downloaded VirtualBox extension pack file name
  debug:
    var: download_result.dest
    verbosity: 1

- name: virtual-box | Install VirtualBox extension pack
  shell: "echo 'y' | VBoxManage extpack install --replace {{ download_result.dest }}"
  