---
- name: chrome | Add repository
  block:
    - name: add public key
      apt_key:
        id: A040830F7FAC5991
        url: https://dl-ssl.google.com/linux/linux_signing_key.pub
        state: present

    - name: add chrome repository
      apt_repository:
        repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
        state: present
        update_cache: true
      with_items: "{{ chrome_repositories }}"
  
- name: chrome | install dependencies
  apt:
    name: "{{ chrome_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"

- name: chrome | configuration for chrome
  block:
    - name: chrome | Create Chrome policies directory for all users
      file:
        path: /etc/chromium/policies/managed
        state: directory

    - name: chrome | Create Chrome JSON policy file to force settings for all users
      copy:
        src: policy.json
        dest: "/etc/chromium/policies/managed/benoth-policy.json"

    - name: chrome | Create Chrome extensions directory for all users
      file:
        path: /usr/share/google-chrome/extensions/
        state: directory

    # See https://developer.chrome.com/extensions/external_extensions#preferences
    - name: chrome | Create Chrome JSON file to install extensions for all users
      template:
        src: chrome-extensions.json.j2
        dest: "/usr/share/google-chrome/extensions/{{ item }}.json"
      with_items:
        - cjpalhdlnbpafiamejdnhcphjbkeiagm # ublock
        - omghfjlpggmjjaagoclmmobgdodcjboh # BrowSec
