---
- name: docker | Add docker repo
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

- name: docker | Add docker repo key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 0EBFCD88
    state: present

- name: docker | Install Docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: docker | adding existing user "{{ lookup('env','USER') }}" to group docker
  user:
    name: "{{ lookup('env','USER') }}"
    groups: docker
    append: true
