---
- name: K8s | Install gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: K8s | Add apt repository for kubectl
  apt_repository:
    repo: deb deb https://apt.kubernetes.io/ kubernetes-focal main
    state: present

- name: K8s | Install kubectl
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - kubectl

- name: K8s | Install minkube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    force: true
    dest: "/usr/local/bin/minikube"
    mode: 0755

- name: K8s | install k9s
  unarchive:
    src: https://github.com/derailed/k9s/releases/download/{{ k9s_ver }}/k9s_Linux_x86_64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755

- name: K8s | install helm
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_ver }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
      - linux-amd64/helm
