---
- name: Install Docker
  include: docker.yml
  tags: [docker]

- name: Install Podman
  include: podman.yml
  tags: [podman]

- name: Install Hashicorp packages
  include: hashicorp.yml
  tags: [hashicorp]

- name: Install RHel packages
  include: rhel.yml
  tags: [rhel]

- name: Install Kubernetes packages
  include: k8s.yml
  tags: [k8s]
