---
- name: Base | install sysutils
  apt:
    name:
      - htop
      - iotop
      - remmina
      - tightvncserver
      - tmate #remote ssh share
      - python3-pip
      - fonts-powerline
    update_cache: yes
    state: latest

- name: Base | install text utility
  snap:
    name:
      - sublime-text
    state: present
    classic: yes
