---
- name: Base | install sysutils
  apt:
    name:
      - htop
      - iotop
      - remmina
      - tightvncserver
      - tmate
      - python3-pip
      - fonts-powerline
    update_cache: true
    state: latest

- name: Base | install text utility
  snap:
    name:
      - sublime-text
    state: present
    classic: true
