---
- name: Networking | install packets
  apt:
    name:
      - wireshark
    state: latest

- name: Networking | Adding group
  group:
    name: wireshark
    state: present

- name: Networking | Adding user to group
  user:
    name: "{{ lookup('env','USER') }}"
    groups: wireshark
    append: true

- name: Networking | Install network utils
  apt:
    name:
      - iftop
      - ifstat
      - iperf
      - ethtool
      - nmap
    state: latest
